const core = 'run'
const specialist = 'plan'
const automation = 'automate'

function module(entry) {
  return {
    type: 'Module',
    status: 'Available',
    hero: '/assets/img/generated/operations-command-story.webp',
    image: '/assets/img/generated/operations-command-story-960.webp',
    imageAlt: `${entry.name} connected FlowIQ workflow`,
    ...entry,
  }
}

export const categoryLabels = {
  all: 'All capabilities',
  run: 'Run the business',
  plan: 'Plan and execute',
  automate: 'Automate and extend',
}

export const modules = [
  module({
    slug: 'dashboardiq',
    name: 'DashboardIQ',
    category: core,
    icon: 'layout-dashboard',
    tagline: 'One operating picture for the whole business.',
    summary: 'Bring sales, margin, stock, cash, branch health, and operational exceptions into one calm executive surface.',
    benefit: 'Managers see what needs attention now instead of waiting for another spreadsheet.',
    image: '/assets/img/modules/thumb-dashboardiq.webp',
    imageAlt: 'DashboardIQ performance and branch dashboard',
    features: ['Executive KPI workspace', 'Branch and period comparison', 'Operational exception visibility', 'Connected module drill-down'],
    workflow: ['Collect live operating signals', 'Compare teams and branches', 'Expose exceptions early', 'Act from connected detail'],
    outcomes: ['Faster management decisions', 'Fewer hidden bottlenecks', 'One shared performance language'],
    connects: ['inventoryiq', 'accountingiq', 'reportsiq'],
  }),
  module({
    slug: 'companiesiq',
    name: 'CompaniesIQ',
    category: core,
    icon: 'building-2',
    tagline: 'Customer and supplier context that travels with every transaction.',
    summary: 'Keep customers, suppliers, contacts, terms, parent groups, credit context, and trading history in one reusable record.',
    benefit: 'Teams stop rebuilding account context across sales, purchasing, service, and finance.',
    image: '/assets/img/modules/thumb-companiesiq.webp',
    imageAlt: 'CompaniesIQ customer and supplier workspace',
    features: ['Customer and supplier records', 'Contacts, terms, and account groups', 'Trading and document history', 'Cross-module relationship context'],
    workflow: ['Create one trusted record', 'Set commercial context', 'Reuse it across workflows', 'Review complete account history'],
    outcomes: ['Cleaner master data', 'Less duplicate administration', 'Faster customer and supplier service'],
    connects: ['salesiq', 'invoiceiq', 'purchaseiq'],
  }),
  module({
    slug: 'salesiq',
    name: 'SalesIQ',
    category: core,
    icon: 'target',
    tagline: 'Turn opportunities and follow-ups into a visible sales rhythm.',
    summary: 'Manage pipelines, opportunities, sales activities, customer follow-ups, voice-note context, and performance visibility.',
    benefit: 'Sales work stays owned, current, and connected to the customer record and revenue process.',
    image: '/assets/img/modules/thumb-salesiq.webp',
    imageAlt: 'SalesIQ pipeline and opportunity workspace',
    features: ['Pipeline and opportunity boards', 'Activities and follow-up ownership', 'Customer timeline context', 'Performance and conversion visibility'],
    workflow: ['Capture the opportunity', 'Plan the next action', 'Move work through the pipeline', 'Hand won work into revenue'],
    outcomes: ['Fewer missed follow-ups', 'Clearer pipeline ownership', 'Cleaner sales-to-invoice handoff'],
    connects: ['companiesiq', 'invoiceiq', 'workiq'],
  }),
  module({
    slug: 'invoiceiq',
    name: 'InvoiceIQ',
    category: core,
    icon: 'file-text',
    tagline: 'Revenue documents with stock, margin, and customer context.',
    summary: 'Move from quote and pro-forma to invoice, credit, payment status, collections, and document history in one controlled trail.',
    benefit: 'Commercial documents stay connected to pricing, inventory cost, customer history, and accounting.',
    image: '/assets/img/modules/thumb-invoiceiq.webp',
    imageAlt: 'InvoiceIQ customer document workspace',
    features: ['Quotes, pro-formas, and invoices', 'Credit notes and payment status', 'Inventory and margin context', 'Source documents and audit history'],
    workflow: ['Prepare the customer document', 'Review price and availability', 'Approve the commercial outcome', 'Track payment and reporting'],
    outcomes: ['Faster document preparation', 'Better margin awareness', 'A cleaner revenue audit trail'],
    connects: ['companiesiq', 'inventoryiq', 'accountingiq'],
  }),
  module({
    slug: 'purchaseiq',
    name: 'PurchaseIQ',
    category: core,
    icon: 'shopping-cart',
    tagline: 'Supplier buying from request to controlled receipt.',
    summary: 'Manage supplier selection, purchase orders, expected cost, approvals, receiving, documents, and supplier follow-up.',
    benefit: 'Buying decisions retain their cost, supplier, approval, and receiving context.',
    image: '/assets/img/modules/thumb-purchaseiq.webp',
    imageAlt: 'PurchaseIQ supplier purchasing workspace',
    features: ['Purchase orders and approvals', 'Supplier document control', 'Expected cost and receiving status', 'Supplier and stock handoff'],
    workflow: ['Identify the buying need', 'Choose and approve the supplier', 'Track the order and documents', 'Receive into the correct workflow'],
    outcomes: ['Stronger purchasing discipline', 'Better expected-cost visibility', 'Fewer receiving handoff gaps'],
    connects: ['companiesiq', 'importiq', 'inventoryiq'],
  }),
  module({
    slug: 'inventoryiq',
    name: 'InventoryIQ',
    category: core,
    icon: 'boxes',
    tagline: 'Stock truth across warehouses, branches, and cost layers.',
    summary: 'Control products, warehouses, bins, FIFO cost layers, transfers, counts, adjustments, kitsets, and stock availability.',
    benefit: 'Teams make decisions from one stock and cost position instead of disconnected counts.',
    image: '/assets/img/modules/thumb-inventoryiq.webp',
    imageAlt: 'InventoryIQ stock and warehouse workspace',
    features: ['Multi-warehouse stock control', 'FIFO cost layers and availability', 'Transfers, counts, and adjustments', 'Kitsets and stock history'],
    workflow: ['Receive stock with cost context', 'Control location and availability', 'Move and count with evidence', 'Feed sales, buying, and finance'],
    outcomes: ['More dependable stock figures', 'Cleaner movement accountability', 'Better purchasing and margin decisions'],
    connects: ['purchaseiq', 'forecastiq', 'invoiceiq'],
  }),
  module({
    slug: 'accountingiq',
    name: 'AccountingIQ',
    category: core,
    icon: 'calculator',
    tagline: 'Financial control that starts with real operations.',
    summary: 'Connect journals, VAT, receivables, payables, bank activity, reconciliation, reporting, and month-end control to daily work.',
    benefit: 'Finance receives an auditable operating trail instead of a disconnected month-end handoff.',
    image: '/assets/img/modules/accountingiq-real-positive.webp',
    imageAlt: 'AccountingIQ financial control dashboard',
    features: ['General ledger and journals', 'VAT, receivables, and payables', 'Bank and reconciliation workflows', 'Financial statements and close control'],
    workflow: ['Receive operational postings', 'Review and reconcile', 'Close with visible exceptions', 'Report from one ledger'],
    outcomes: ['Cleaner financial truth', 'Better month-end confidence', 'Stronger auditability'],
    connects: ['invoiceiq', 'purchaseiq', 'journaliq'],
  }),
  module({
    slug: 'reportsiq',
    name: 'ReportsIQ',
    category: core,
    icon: 'file-bar-chart',
    tagline: 'Decision-ready reporting from the work already done.',
    summary: 'Create structured operational, customer, supplier, inventory, and finance reporting from connected FlowIQ data.',
    benefit: 'Management packs and drill-downs stay aligned to the underlying workflow.',
    image: '/assets/img/modules/thumb-reportsiq.webp',
    imageAlt: 'ReportsIQ management reporting workspace',
    features: ['Operational and financial reports', 'Customer and supplier views', 'Inventory and performance analysis', 'Exportable management packs'],
    workflow: ['Choose the decision lens', 'Prepare connected data', 'Compare the right dimensions', 'Share and act'],
    outcomes: ['Less spreadsheet rework', 'More trusted management packs', 'Faster performance review'],
    connects: ['dashboardiq', 'accountingiq', 'inventoryiq'],
  }),

  module({
    slug: 'importiq',
    name: 'ImportIQ',
    category: specialist,
    icon: 'ship',
    tagline: 'True landed cost from supplier order to received stock.',
    summary: 'Manage import shipments, supplier documents, freight, duty, FX, VAT, consolidations, landed-cost allocation, and receiving.',
    benefit: 'Imported stock reaches pricing and finance with its true cost story intact.',
    hero: '/assets/img/generated/importiq-story.webp',
    image: '/assets/img/modules/thumb-importiq.webp',
    imageAlt: 'ImportIQ landed-cost and shipment workspace',
    features: ['Shipment and consolidation control', 'Freight, duty, FX, and VAT', 'Landed-cost allocation', 'Receiving and accounting handoff'],
    workflow: ['Start from the supplier order', 'Build the shipment cost stack', 'Review true landed cost', 'Receive and protect margin'],
    outcomes: ['More accurate landed cost', 'Fewer hidden import charges', 'Better pricing and margin control'],
    connects: ['purchaseiq', 'inventoryiq', 'priceiq'],
  }),
  module({
    slug: 'exportiq',
    name: 'ExportIQ',
    category: specialist,
    icon: 'plane-takeoff',
    tagline: 'Export progress, documents, and currency context in one trail.',
    summary: 'Manage export shipment records, document readiness, milestones, customer context, and foreign-currency inflow visibility.',
    benefit: 'Export teams can see what is ready, what is blocked, and which documents still need attention.',
    image: '/assets/img/modules/thumb-exportiq.webp',
    imageAlt: 'ExportIQ shipment and document workspace',
    features: ['Export shipment records', 'Milestones and readiness status', 'Document and customer context', 'Foreign-currency inflow visibility'],
    workflow: ['Open the export record', 'Prepare shipment documents', 'Track milestones and exceptions', 'Close the commercial trail'],
    outcomes: ['Clearer export readiness', 'Fewer document gaps', 'Better shipment accountability'],
    connects: ['salesiq', 'invoiceiq', 'accountingiq'],
  }),
  module({
    slug: 'forecastiq',
    name: 'ForecastIQ',
    category: specialist,
    icon: 'trending-up',
    tagline: 'Turn stock history into better buying decisions.',
    summary: 'Use demand history, seasonality, stock pressure, slow movers, and replenishment signals to plan purchasing and production.',
    benefit: 'Buyers see risk early enough to act instead of reacting after a stockout or overbuy.',
    hero: '/assets/img/generated/inventory-forecast-story.webp',
    image: '/assets/img/modules/thumb-forecastiq.webp',
    imageAlt: 'ForecastIQ demand and replenishment workspace',
    features: ['Demand and seasonal analysis', 'Reorder and stockout signals', 'Slow and dead stock visibility', 'Purchasing and production context'],
    workflow: ['Read demand history', 'Expose stock pressure', 'Review recommended action', 'Feed buying or production'],
    outcomes: ['Fewer avoidable stockouts', 'Less cash trapped in slow stock', 'More disciplined replenishment'],
    connects: ['inventoryiq', 'purchaseiq', 'manufacturing'],
  }),
  module({
    slug: 'priceiq',
    name: 'PriceIQ',
    category: specialist,
    icon: 'badge-dollar-sign',
    tagline: 'Pricing decisions grounded in cost and margin.',
    summary: 'Manage price lists, customer pricing, landed-cost context, margin review, discount visibility, and controlled price changes.',
    benefit: 'Teams can price with context instead of relying on stale cost assumptions.',
    image: '/assets/img/modules/thumb-priceiq.webp',
    imageAlt: 'PriceIQ price and margin workspace',
    features: ['Price-list management', 'Cost and landed-cost context', 'Margin and discount review', 'Customer pricing control'],
    workflow: ['Read the current cost base', 'Model the price and margin', 'Review exceptions', 'Publish the approved position'],
    outcomes: ['Better margin protection', 'Faster price reviews', 'Clearer discount accountability'],
    connects: ['importiq', 'inventoryiq', 'invoiceiq'],
  }),
  module({
    slug: 'manufacturing',
    name: 'Manufacturing',
    category: specialist,
    icon: 'factory',
    tagline: 'Production control from BOM to finished-goods cost.',
    summary: 'Manage bills of materials, work orders, component usage, FIFO consumption, finished-goods layers, and WIP journal outputs.',
    benefit: 'Production, stock, and accounting share the same view of what was consumed and created.',
    image: '/assets/img/modules/thumb-manufacturing.webp',
    imageAlt: 'FlowIQ manufacturing and work-order workspace',
    features: ['BOM and component control', 'Work orders and execution status', 'FIFO material consumption', 'Finished goods and WIP outputs'],
    workflow: ['Define the product structure', 'Release the work order', 'Consume and record production', 'Receive finished goods and journals'],
    outcomes: ['More dependable production cost', 'Cleaner material traceability', 'Stronger stock-to-finance handoff'],
    connects: ['inventoryiq', 'forecastiq', 'journaliq'],
  }),
  module({
    slug: 'projectsiq',
    name: 'ProjectsIQ',
    category: specialist,
    icon: 'folder-kanban',
    tagline: 'Project work, cost, ownership, and proof in one workspace.',
    summary: 'Group project status, milestones, ownership, budgets, tasks, time, attachments, and operational context around the job.',
    benefit: 'Project teams can see delivery progress and commercial pressure without stitching together separate tools.',
    image: '/assets/img/modules/thumb-projectsiq.webp',
    imageAlt: 'ProjectsIQ project workspace',
    features: ['Project status and ownership', 'Milestones, tasks, and attachments', 'Budget and cost context', 'Time and delivery visibility'],
    workflow: ['Create the project frame', 'Assign milestones and ownership', 'Track work and evidence', 'Review delivery and cost'],
    outcomes: ['Clearer project accountability', 'Less scattered proof', 'Better delivery and cost visibility'],
    connects: ['workiq', 'timeiq', 'reportsiq'],
  }),
  module({
    slug: 'ecomiq',
    name: 'EcomIQ',
    category: specialist,
    icon: 'shopping-bag',
    tagline: 'Connect online demand to stock and fulfilment.',
    summary: 'Manage ecommerce product, catalog, media, sync, channel visibility, orders, stock pressure, and fulfilment context.',
    benefit: 'Online operations stop behaving like a separate island from inventory, invoicing, and finance.',
    hero: '/assets/img/generated/ecommerce-retail-story.webp',
    image: '/assets/img/modules/ecomiq-real.webp',
    imageAlt: 'EcomIQ ecommerce operations workspace',
    features: ['Catalog and product readiness', 'Channel and sync visibility', 'Order and stock context', 'Fulfilment and invoice handoff'],
    workflow: ['Prepare the catalog', 'Connect channel demand', 'Reserve and fulfil stock', 'Close the revenue trail'],
    outcomes: ['Cleaner channel operations', 'Better stock availability', 'Less manual order re-entry'],
    connects: ['inventoryiq', 'invoiceiq', 'accountingiq'],
  }),
  module({
    slug: 'payrolliq',
    name: 'PayrollIQ',
    category: specialist,
    icon: 'users-round',
    tagline: 'Payroll, leave, and employee records with finance context.',
    summary: 'Manage employees, pay runs, leave, payslips, approvals, payroll history, and configured statutory and accounting outputs.',
    benefit: 'Payroll work stays reviewable and connected to the wider finance and people record.',
    image: '/assets/img/modules/thumb-payrolliq.webp',
    imageAlt: 'PayrollIQ pay-run and employee workspace',
    features: ['Employee and payroll records', 'Pay runs and payslips', 'Leave and approval workflows', 'Accounting and configured statutory outputs'],
    workflow: ['Maintain employee context', 'Prepare the pay run', 'Review and approve', 'Publish outputs and journals'],
    outcomes: ['More controlled pay runs', 'Clearer employee history', 'Cleaner payroll-to-finance handoff'],
    connects: ['timeiq', 'accountingiq', 'reportsiq'],
  }),
  module({
    slug: 'cashiq',
    name: 'CashIQ',
    category: specialist,
    icon: 'wallet-cards',
    tagline: 'Petty cash and cash sales with source proof.',
    summary: 'Track warehouse petty cash, cash received, cash sales, spend invoices, attachments, approvals, and reconciliation context.',
    benefit: 'Small cash movements receive the same ownership and evidence discipline as larger transactions.',
    image: '/assets/img/generated/finance-decision-story-960.webp',
    imageAlt: 'CashIQ finance and cash-control story',
    features: ['Cash sales and receipts', 'Petty-cash movements', 'Spend invoices and attachments', 'Approval and reconciliation context'],
    workflow: ['Capture the movement', 'Attach the proof', 'Review allocation and VAT', 'Reconcile and close'],
    outcomes: ['Less lost cash evidence', 'Cleaner petty-cash control', 'Faster reconciliation'],
    connects: ['slipiq', 'accountingiq', 'reportsiq'],
  }),
  module({
    slug: 'journaliq',
    name: 'JournalIQ',
    category: specialist,
    icon: 'book-open-check',
    tagline: 'Reviewable journals with operational context.',
    summary: 'Manage manual journals, accounting adjustments, WIP and finished-goods postings, queues, retry status, and audit history.',
    benefit: 'Adjustments remain traceable to the workflow that caused them.',
    image: '/assets/img/modules/thumb-journaliq.webp',
    imageAlt: 'JournalIQ journal queue workspace',
    features: ['Manual journal entries', 'WIP and finished-goods outputs', 'Queue and retry visibility', 'Posting audit trail'],
    workflow: ['Prepare the journal context', 'Review accounts and values', 'Post through the controlled queue', 'Inspect the audit result'],
    outcomes: ['Fewer unexplained adjustments', 'Stronger posting control', 'Cleaner finance audit trails'],
    connects: ['accountingiq', 'manufacturing', 'payrolliq'],
  }),
  module({
    slug: 'warrantyiq',
    name: 'WarrantyIQ',
    category: specialist,
    icon: 'shield-check',
    tagline: 'Claims, assessment, stock, and customer context together.',
    summary: 'Manage warranty claims, customer context, assessment, evidence, outcomes, replacements, and claim history.',
    benefit: 'Returns and warranty decisions stay connected to the original product, customer, stock, and cost trail.',
    image: '/assets/img/modules/thumb-warrantyiq.webp',
    imageAlt: 'WarrantyIQ claim assessment workspace',
    features: ['Claim intake and customer context', 'Assessment and evidence', 'Outcome and replacement control', 'Complete claim history'],
    workflow: ['Open the claim', 'Inspect source and evidence', 'Approve the outcome', 'Close stock and customer actions'],
    outcomes: ['Faster claim resolution', 'Clearer replacement control', 'Better warranty history'],
    connects: ['companiesiq', 'inventoryiq', 'invoiceiq'],
  }),
  module({
    slug: 'workiq',
    name: 'WorkIQ',
    category: specialist,
    icon: 'briefcase-business',
    tagline: 'Client work and staff execution in visible queues.',
    summary: 'Use job cards, work queues, subtasks, attachments, client ledgers, staff activity, and delivery status to control service work.',
    benefit: 'Teams see what is waiting, who owns it, and what proof or action is still required.',
    image: '/assets/img/generated/business-command-story.webp',
    imageAlt: 'WorkIQ service work and team execution story',
    features: ['Job cards and work queues', 'Subtasks and attachments', 'Client work ledgers', 'Staff activity and progress'],
    workflow: ['Create the work item', 'Assign ownership and subtasks', 'Collect progress and proof', 'Review delivery and outstanding work'],
    outcomes: ['Less work lost between teams', 'Clearer service ownership', 'Better client delivery visibility'],
    connects: ['timeiq', 'taskiq', 'projectsiq'],
  }),
  module({
    slug: 'timeiq',
    name: 'TimeIQ',
    category: specialist,
    icon: 'clock-3',
    tagline: 'Time, attendance, and approvals connected to work.',
    summary: 'Track time, attendance, shift context, work-item allocation, approvals, and payroll or finance handoff where configured.',
    benefit: 'Recorded time becomes usable operational and cost context instead of an isolated timesheet.',
    image: '/assets/img/generated/business-command-story.webp',
    imageAlt: 'TimeIQ time and attendance operating story',
    features: ['Time and attendance records', 'Shift and work-item context', 'Review and approval flows', 'Payroll and finance handoff'],
    workflow: ['Capture time against the right context', 'Review exceptions', 'Approve the period', 'Feed payroll or project reporting'],
    outcomes: ['Cleaner timesheets', 'Better labour visibility', 'Faster approval cycles'],
    connects: ['workiq', 'payrolliq', 'projectsiq'],
  }),
  module({
    slug: 'taskiq',
    name: 'TaskIQ',
    category: specialist,
    icon: 'list-checks',
    tagline: 'Owned work, due dates, proof, and review queues.',
    summary: 'Track work that needs ownership, due dates, priority, notes, attachments, recurring schedules, review, and completion status.',
    benefit: 'Follow-through becomes visible across teams and modules.',
    image: '/assets/img/modules/thumb-taskiq.webp',
    imageAlt: 'TaskIQ task and workflow workspace',
    features: ['Personal and assigned queues', 'Due dates and priority', 'Notes, checklists, and attachments', 'Recurring work and review status'],
    workflow: ['Create the required action', 'Assign owner and due date', 'Complete with context or proof', 'Review and close'],
    outcomes: ['Fewer dropped actions', 'Clearer ownership', 'A stronger completion trail'],
    connects: ['workiq', 'projectsiq', 'dashboardiq'],
  }),
  module({
    slug: 'deliveryiq',
    name: 'DeliveryIQ',
    category: specialist,
    icon: 'truck',
    tagline: 'Own-delivery execution from dispatch to completion.',
    summary: 'Track delivery work, route and vehicle context, dispatch readiness, in-progress stops, exceptions, costs, and completion proof.',
    benefit: 'Operations can see what needs dispatch, what is moving, and what is blocked.',
    image: '/assets/img/generated/operations-command-story-960.webp',
    imageAlt: 'DeliveryIQ delivery and route operations story',
    features: ['Dispatch and delivery queues', 'Route, vehicle, and driver context', 'Status, ETA, and exception visibility', 'Completion and delivery proof'],
    workflow: ['Build the delivery queue', 'Assign route and ownership', 'Track progress and exceptions', 'Complete with proof'],
    outcomes: ['Clearer dispatch control', 'Better delivery visibility', 'Faster exception response'],
    connects: ['invoiceiq', 'companiesiq', 'dashboardiq'],
  }),
  module({
    slug: 'courieriq',
    name: 'CourierIQ',
    category: specialist,
    icon: 'send',
    tagline: 'Compare courier options before making the shipping decision.',
    summary: 'Use address, parcel, provider, quote, booking, label, and tracking context to manage third-party courier workflows.',
    benefit: 'Teams can compare practical shipping options without losing the commercial and delivery context.',
    image: '/assets/img/generated/operations-command-story-960.webp',
    imageAlt: 'CourierIQ courier comparison and shipping story',
    features: ['Provider and service comparison', 'Parcel and address context', 'Quote and booking workflow', 'Label and tracking visibility'],
    workflow: ['Prepare shipment details', 'Compare available services', 'Approve and book', 'Track the external delivery'],
    outcomes: ['Faster shipping decisions', 'Clearer courier cost context', 'Less disconnected tracking'],
    connects: ['invoiceiq', 'deliveryiq', 'companiesiq'],
  }),

  module({
    slug: 'ai-auto-capture',
    name: 'AI Auto Capture',
    category: automation,
    type: 'Add-on',
    icon: 'sparkles',
    tagline: 'Review-ready documents. Human-controlled outcomes.',
    summary: 'Capture customer orders, supplier documents, slips, cash invoices, import and freight documents, and sales voice notes while keeping a person in control.',
    benefit: 'Teams reduce re-keying without allowing an email or model response to post a commercial document automatically.',
    hero: '/assets/img/auto-capture/customer-upload.png',
    image: '/assets/img/auto-capture/supplier-review.png',
    imageAlt: 'FlowIQ Supplier Auto Capture review with mapping confidence, warnings, and draft controls',
    features: ['Email and upload intake', 'Attachment-level auto-split', 'Source-linked extraction and mapping', 'Explicit review before draft creation', 'Organization-scoped mapping memory', 'Pending-queue and bell notifications'],
    workflow: ['Receive or upload the source', 'Create one queue item per attachment', 'Extract and propose mappings', 'Review against the source', 'Create the approved draft'],
    outcomes: ['Less manual re-keying', 'A safer email-to-draft workflow', 'Reusable reviewed mappings'],
    connects: ['invoiceiq', 'purchaseiq', 'slipiq'],
    faq: [
      ['What does auto-split mean?', 'Each supported email attachment becomes its own independently reviewable queue item. A three-attachment email creates three items; FlowIQ does not silently split a multi-document PDF into guessed page ranges.'],
      ['Does an incoming email create an order automatically?', 'No. Email receipt creates a source-linked review item. A user must check fields, map customer or supplier and products, then explicitly create the normal pro-forma or draft purchase order.'],
      ['How are customer and supplier documents kept apart?', 'Use separate recipient aliases, or separate Google mailbox labels. FlowIQ follows the configured route and does not guess whether a document belongs in InvoiceIQ or PurchaseIQ.'],
      ['How does FlowIQ keep the process safe?', 'Items are organization-scoped and deduplicated, source evidence remains available during review, uncertain mappings stay visible, and no commercial posting occurs from intake alone.'],
    ],
    releaseNote: 'Incoming email monitoring uses a connected Google mailbox with read-only access. Wider availability depends on Google restricted-scope approval. Auto Capture remains review-first while real-document certification evidence continues to grow.',
  }),
  module({
    slug: 'agentsiq',
    name: 'AgentsIQ',
    category: automation,
    type: 'Add-on',
    icon: 'bot',
    tagline: 'AI-assisted operational work with approvals and guardrails.',
    summary: 'Monitor agent activity, review suggestions, manage exceptions, and keep AI-assisted work aligned with FlowIQ permissions.',
    benefit: 'Automation can help teams prepare and prioritize work without bypassing the people accountable for it.',
    image: '/assets/img/generated/flowiq-control-room-960.webp',
    imageAlt: 'AgentsIQ supervised automation control room',
    features: ['Agent activity visibility', 'Reviewable suggestions and outputs', 'Permission-aligned actions', 'Exceptions and approval guardrails'],
    workflow: ['Detect the relevant signal', 'Prepare a suggested action', 'Route it for review', 'Approve or reject with context'],
    outcomes: ['Faster operational follow-up', 'Safer use of AI assistance', 'Clearer automation accountability'],
    connects: ['ai-auto-capture', 'taskiq', 'dashboardiq'],
  }),
  module({
    slug: 'slipiq',
    name: 'SlipIQ',
    category: automation,
    type: 'Included with AI Auto Capture',
    icon: 'receipt',
    tagline: 'Expense slips from capture to reviewed allocation.',
    summary: 'Capture till slips and receipts, review extracted lines and VAT, allocate the expense, retain source proof, and complete the history.',
    benefit: 'Small receipts stop disappearing into inboxes, wallets, and month-end catch-up.',
    image: '/assets/img/auto-capture/slip-review.png',
    imageAlt: 'SlipIQ receipt review and allocation workflow',
    features: ['Photo and document capture', 'Line, VAT, and total review', 'Expense allocation context', 'Source proof and completion history'],
    workflow: ['Capture the receipt', 'Review fields and totals', 'Allocate the expense', 'Approve and retain the proof'],
    outcomes: ['Less lost receipt evidence', 'Faster expense capture', 'Cleaner VAT and allocation review'],
    connects: ['ai-auto-capture', 'cashiq', 'accountingiq'],
  }),
  module({
    slug: 'rfid-stock-tracking',
    name: 'RFID Stock Tracking',
    category: automation,
    type: 'Add-on',
    icon: 'scan-line',
    tagline: 'Scan evidence and supervised stock-movement control.',
    summary: 'Use RFID events, zones, readers, stocktake evidence, movement alerts, and supervised review queues to strengthen stock execution.',
    benefit: 'High-volume movement becomes easier to evidence and review without letting raw scanner events rewrite stock blindly.',
    image: '/assets/img/generated/operations-command-story-960.webp',
    imageAlt: 'RFID stock movement and supervised review story',
    features: ['RFID reader and zone context', 'Stocktake and movement evidence', 'Rapid-movement and SLA alerts', 'Supervised review queues'],
    workflow: ['Collect scan evidence', 'Classify the movement signal', 'Review exceptions and suggested action', 'Commit through the normal stock control'],
    outcomes: ['Faster stock evidence capture', 'Better movement traceability', 'Safer warehouse automation'],
    connects: ['inventoryiq', 'dashboardiq', 'taskiq'],
  }),
  module({
    slug: 'posiq',
    name: 'POSIQ',
    category: automation,
    type: 'Add-on',
    icon: 'monitor-smartphone',
    tagline: 'Connect till activity to FlowIQ stock and finance.',
    summary: 'Bring configured point-of-sale activity into the wider product, price, stock, branch, cash, and accounting story.',
    benefit: 'Retail trading activity can share the same operational truth as the rest of the business.',
    image: '/assets/img/generated/ecommerce-retail-story-960.webp',
    imageAlt: 'POSIQ retail and till integration story',
    features: ['Till and branch context', 'Product and price alignment', 'Stock and cash handoff', 'Finance and reporting visibility'],
    workflow: ['Connect the configured till source', 'Align product and branch context', 'Review operational handoff', 'Report with the wider business'],
    outcomes: ['Less retail data re-entry', 'Better branch visibility', 'Cleaner POS-to-finance context'],
    connects: ['inventoryiq', 'cashiq', 'accountingiq'],
  }),
  module({
    slug: 'accounting-reconciliation',
    name: 'Accounting Reconciliation',
    category: automation,
    type: 'Add-on',
    icon: 'landmark',
    tagline: 'Make matching and reconciliation a review workflow.',
    summary: 'Use imported bank activity, suggested matches, exception handling, allocation context, and controlled confirmation to accelerate reconciliation.',
    benefit: 'Finance spends less time searching and more time resolving the exceptions that matter.',
    image: '/assets/img/generated/finance-decision-story-960.webp',
    imageAlt: 'Accounting reconciliation and matching workflow',
    features: ['Bank activity import', 'Suggested transaction matches', 'Exception and allocation review', 'Controlled reconciliation confirmation'],
    workflow: ['Bring in the bank activity', 'Prepare candidate matches', 'Review exceptions and allocation', 'Confirm the reconciled result'],
    outcomes: ['Faster reconciliation', 'Fewer unexplained differences', 'A clearer matching trail'],
    connects: ['accountingiq', 'invoiceiq', 'purchaseiq'],
  }),
  module({
    slug: 'commission-rebate-automation',
    name: 'Commission & Rebate Automation',
    category: automation,
    type: 'Add-on',
    icon: 'percent',
    tagline: 'Control complex commissions, rebates, and exceptions.',
    summary: 'Import commission or rebate data, apply configured rules, surface missing or conflicting amounts, and review payout or settlement outcomes.',
    benefit: 'Teams can replace opaque spreadsheets with an exception-led, auditable process.',
    image: '/assets/img/generated/finance-decision-story-960.webp',
    imageAlt: 'Commission and rebate automation workflow',
    features: ['Commission and rebate imports', 'Configured calculation rules', 'Missing-payment and exception detection', 'Reviewed payout and settlement trail'],
    workflow: ['Import the source data', 'Apply the configured rule set', 'Review exceptions', 'Approve the final outcome'],
    outcomes: ['Less manual calculation work', 'Faster exception discovery', 'More defensible settlements'],
    connects: ['salesiq', 'accountingiq', 'reportsiq'],
  }),
  module({
    slug: 'business-units',
    name: 'Business Units',
    category: automation,
    type: 'Add-on',
    icon: 'network',
    tagline: 'Operate multiple units without losing group visibility.',
    summary: 'Separate operational context by branch or business unit while retaining controlled group-level reporting, access, and shared governance.',
    benefit: 'Growing groups can preserve local accountability and still understand the whole business.',
    image: '/assets/img/generated/business-command-story.webp',
    imageAlt: 'FlowIQ multi-business-unit operating story',
    features: ['Business-unit and branch context', 'Scoped operational visibility', 'Group-level comparison', 'Shared governance and reporting'],
    workflow: ['Define the operating units', 'Scope users and transactions', 'Run local workflows', 'Compare and govern at group level'],
    outcomes: ['Clearer unit accountability', 'Safer access boundaries', 'Better group visibility'],
    connects: ['dashboardiq', 'companiesiq', 'reportsiq'],
  }),
]

export const moduleBySlug = new Map(modules.map((entry) => [entry.slug, entry]))
